azure_dbt_snowflake_project:
  outputs:
    dev:
      account: ****************.snowflakecomputing.com
      database: AIRBNB
      password: ****************
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: sindisiwe
      warehouse: COMPUTE_WH
  target: dev